### ISSUE TITLE
Document the lifecycle of LB

### ISSUE THREAD

**Issue by StarpTech** [hetznercloud/hcloud-cloud-controller-manager#104]
Hello,
I'm looking for a solution to preserve a load balancer IP. Currently, when I remove the LoadBalancer service the LB is removed. Other providers like Linode provide [annotations](https://github.com/linode/linode-cloud-controller-manager#annotations) `preserve`, `nodebalancer-id` to control that.

**Comment by StarpTech** [comment]
I observed the behavior that specifying `load-balancer.hetzner.cloud/name: "traefik"` will preserve the IP. Is that intentional?

**Comment by LKaemmerling** [comment]
You can reuse a Load Balancer by using `load-balancer.hetzner.cloud/name` or `load-balancer.hetzner.cloud/id` annotation (https://pkg.go.dev/github.com/hetznercloud/hcloud-cloud-controller-manager/internal/annotation#Name). 

You should also activate the `deletion protection` within the Hetzner Cloud UI otherwise, the Loadbalancer would be deleted when you delete the service.

Please also keep in mind that the Cloud Controller always overwrites all changes on the Load Balancer (deletion protection is excluded, as this is not controllable via the Cloud Controller Manager), so when you add a Load Balancer service manually through the cloud console, the Cloud Controller Manager will delete this service.

**Comment by StarpTech** [comment]
Thanks for the info.

**Comment by StarpTech** [comment]
I think it might help others to document this.
