### ISSUE TITLE
Support IPv6 for loadbalancers

### ISSUE THREAD

**Issue by morremeyer** [hetznercloud/hcloud-cloud-controller-manager#121]
In the code for the load balancers, there are multiple lines that would indicate IPv6 support is ready and „just needs to be enabled“.

Those are:

* [getting the status](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/be4b286969da99eade775af99452d6b87a9a5f73/hcloud/load_balancers.go#L147-L149)
* [setting the IPs](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/be4b286969da99eade775af99452d6b87a9a5f73/hcloud/load_balancers.go#L58-L60)

Could you clarify the reason why the lines are commented? As far as I know, the upstream implementation supports IPv6 addresses on Ingresses.

Once I understand the issue, I’ll gladly extend the docs/the comment to clarify this for the next person.

**Comment by LKaemmerling** [comment]
Hey @morremeyer,

our Load Balancers support IPv6 out of the box. We commented the lines because the IPv6 Support within k8s is currently in alpha stage and therefore not "ready". While developing the CCM we encountered a few issues with IPv6 & k8s and therefore decided to "leave it out" for the moment. Maybe we can add an annotation to enable/disable IPv6 Support.
