### ISSUE TITLE
Same loadbalancer for different services?

### ISSUE THREAD

**Issue by JannikZed** [hetznercloud/hcloud-cloud-controller-manager#138]
Hi there,
I was trying to use the same loadbalancer name across different services - which somehow completely bricked our stack.. when deleting some of the services, the one loadbalancer got deleted in Hetzner, making our whole cluster unavailable ..

I thought: one loadbalancer is able to handle 5 different services. Why couldn't that be 5 different services in Kubernetes?

**Comment by LKaemmerling** [comment]
Hey @JannikZed,

K8s works mostly with a reconciliation loop system. So it seems, that within the load balancer is something other defined than within the k8s service definition and then it tries to update it. We decided to don't add a possibility around this, as it might come with more problems than it solves. You could use an in-cluster ingress as a target behind the LB, then it should be possible to use the same LB with multiple ports, but keep in mind that all ports need to be accessible from all nodes that are added as targets to the LB.

**Comment by schamane** [comment]
I had simmilar request for that. In my opinion LB is currently good for Hetzner Cloud, but not for K8s on Hetzner Cloud.

I ended with solution to have in-cluster ingress.

Thats not true. I run in-cluster ingress only on one node (replicaset = 1) because of persistancy for ingress pod. And its runs fine. LB is capable to identify node where port is open and working and route all request only to one node.
