### ISSUE TITLE
Policy/schedule for new releases

### ISSUE THREAD

**Issue by morremeyer** [hetznercloud/hcloud-cloud-controller-manager#151]
As I wanted to have the IPv6 support for Load Balancers, I forked the repository and updated the CI to build a docker image on [my GitLab instance](https://git.mor.re/docker-images/hcloud-cloud-controller-manager/).

I deployed the resulting image successfully to a cluster of mine, so I was wondering how your current policy for a new release is?

It would be nice to have the IPv6 support for LBs without updating my fork every now and then.

At the same time, I noticed an issue with external-dns once the current master (f6042f0e83bf7cb5eb3e1e2a7f6dbff04e33fbbd) is deployed: It seems to „get confused“ by the additional IPv6 address and then „update“ all records on each run, but it does not actually change anything. (so the only impact is a lot of log messages from external-dns).

Is that something you’d want to get fixed in external-dns before putting out a new release of the CCM so that the user experience is not diminished or would you rather release a new version to make the debugging of external-dns easier?

I’m up for either variant as I’ll probably debug the external-dns issue soon anyways, but I’d be happy to get an insight into how you handle those things.

**Comment by LKaemmerling** [comment]
Hey @morremeyer,

we plan to release a new version in the next couple of weeks. There is no real release schedule/cycle, we normally group a lot of enhancements in a single release (if it is not a bugfix release). 

If you always want to be bleeding edge, you can use the master/dev deployment (https://github.com/hetznercloud/hcloud-cloud-controller-manager/tree/master/deploy `dev-*` deployment files), the master branch is always stable itself because we won't merge/commit untested stuff there. 

As I said, I expect a new release in a couple of weeks because of some stuff we are working on :)

**Comment by morremeyer** [comment]
Great, thanks for the info. Will switch to `dev-*` now and then go back to the next release once it’s there.
