### ISSUE TITLE
Running the CCM out-of-cluster

### ISSUE THREAD

**Issue by xrstf** [hetznercloud/hcloud-cloud-controller-manager#159]
When provisioning a Kubernetes cluster, we run the control plane and related components (e.g. Prometheus) outside of the cluster itself. This is also where we want to deploy the hcloud-CCM, but noticed that it currently requires the `NODE_NAME` variable to be set.

Judging from the code, it's currently only used in tests to determine the correct zone. For now we can therefore simply give a dummy value to the CCM, but are afraid that this might change in future versions.

What's the plan moving forward on this? Would it be, for example, possible to define another `HCLOUD_ZONE` variable that can be set to disable the auto-detection?

**Comment by LKaemmerling** [comment]
Hey @xrstf,
Thank you for your issue!

On a first look, i would think we can remove it easily, as the CCM does not need to know where it runs on. I will look deeper into it in the next few days. 
cc @fhofherr

**Comment by LKaemmerling** [comment]
Okay, I looked a bit more into it, @xrstf removing it is not that easily possible. It is always required because based on this, the zone will be set. I guess adding a `HCLOUD_ZONE` env would be an idea, even if I'm not completely sure if this is a really good solution. I will talk with a few colleagues about it and then come back to you.
