### ISSUE TITLE
hcops/AllServersCache.getCache: not found

### ISSUE THREAD

**Issue by mfrister** [hetznercloud/hcloud-cloud-controller-manager#165]
@vitobotta and @xrstf reported this in #107 (which is related to a different problem):

@vitobotta:
> Actually my message is slightly different, it doesn't mention specific IPs:
> 
> ```
>  Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/hcloudRouteToRoute: hcops/AllSer
> ```

@xrsftf:
> We are experiencing the same error:
> 
> > Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/hcloudRouteToRoute: hcops/AllServersCache.ByPrivateIP: hcops/AllServersCache.getCache: not found
> 
> ... and would like to know if we can ignore it.

**Comment by LKaemmerling** [comment]
Hey @vitobotta  nad @xrstf 

I tried to debug the issue a bit deeper. I would need a bit more information about your clusters.

Do you use our Networks Feature (Deployment of CCM with networks)?

Can you give us information about your network topology? It looks like you reference a server as "gateway" that is not a real hetzner cloud server in some routes.

**Comment by xrstf** [comment]
Yes, we are using the CCM with a `HCLOUD_NETWORK` env var specified. Our network topology is rather simple. We use KubeOne with Terraform to create a few cloud servers and that's mostly it. There are no bastion hosts / proxies, all 6 machines are equal w.r.t. to their networking.

Is this helpful?

![screenshot-2021-03-17-145716](https://user-images.githubusercontent.com/127499/111479572-64401280-8731-11eb-9b82-8fa099f4b027.png)

![screenshot-2021-03-17-145744](https://user-images.githubusercontent.com/127499/111479590-67d39980-8731-11eb-9e9d-116388f977bb.png)

**Comment by LKaemmerling** [comment]
Hey @xrstf,

can you please try out the latest dev build? I added a bit more logging which helps us finding the problem:)

**Comment by xrstf** [comment]
Funny enough, we have since recreated our clusters and switched from Nürnberg to Helsinki. Looking at the logs, the error does not happen for us anymore with 1.5.0.So ... sorry, we cannot reproduce this anymore at the moment.

**Comment by ErwinSteffens** [comment]
I have some extra logging from the dev build. 

```
ERROR: logging before flag.Parse: E0413 07:35:36.982052       1 route_controller.go:120] Couldn't reconcile node routes: error listing routes: server with IP 10.0.0.2 not found
```

This server does not exist anymore, but the route is still there:

![image](https://user-images.githubusercontent.com/6931114/114514728-e3930a00-9c3b-11eb-9d73-473864878118.png)

**Comment by marcispauls** [comment]
Hi Team,
i can also confirm that i have similar issue.
It happens when cloud autoscaler scales down cluster. Worker node doesnt exist anymore but route still exists in the UI.

**Comment by Floppy012** [comment]
I've looked a little bit into it. The problem is (as already written above) that if a Node is deleted, the route will not be deleted immediately. It seems they are only deleted when a [full resync](https://github.com/kubernetes/cloud-provider/blob/1ea896ed6b0df6e982baa0bc7d46b92c98e7161d/controllers/route/route_controller.go#L111) is done. This is also where the error we see gets logged.

Since the problem is, that we have a route we no longer have a node for, I had a look at how `route.TargetNode` is handled. And it seems like they expect that it could be an [empty string](https://github.com/kubernetes/cloud-provider/blob/1ea896ed6b0df6e982baa0bc7d46b92c98e7161d/controllers/route/route_controller.go#L144). I haven't tested it but if I didn't oversee something then the route should be deleted if `route.TargetNode` is an empty string since the [`nodeRouteStatuses`](https://github.com/kubernetes/cloud-provider/blob/1ea896ed6b0df6e982baa0bc7d46b92c98e7161d/controllers/route/route_controller.go#L228) shouldn't contain anything with an empty string as key [`nodeHasCidr`](https://github.com/kubernetes/cloud-provider/blob/1ea896ed6b0df6e982baa0bc7d46b92c98e7161d/controllers/route/route_controller.go#L230) would return `false` which would cause the [route to be deleted](https://github.com/kubernetes/cloud-provider/blob/1ea896ed6b0df6e982baa0bc7d46b92c98e7161d/controllers/route/route_controller.go#L239).

In addition to that `route.Blackhole` could be set to `true` which would omit the `nodeHasCidr` check.
