### ISSUE TITLE
Fork of digitalocean-cloud-controller-manager?

### ISSUE THREAD

**Issue by AlekSi** [hetznercloud/hcloud-cloud-controller-manager#2]
Hi. I could not help myself but notice that hcloud-cloud-controller-manager looks very similar to https://github.com/digitalocean/digitalocean-cloud-controller-manager, yet copyrights are different. Did you use some kind of common skeleton project? Or you took DigitalOcean's code and replaced copyrights with your own?

**Comment by thetechnick** [comment]
We do not share code with the digital ocean repository.
The `main.go` file which is derived in both implementations from the kubernetes projects `controller-manager.go` file: https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/controller-manager.go
Which should be used for this purpose:
https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/

Other similarities are due to the fact that there are only so many ways to sanely implement the same functionality.

**Comment by AlekSi** [comment]
> The main.go file which is derived in both implementations from the kubernetes projects controller-manager.go file: https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/controller-manager.go

It looks very different to me.

> Other similarities are due to the fact that there are only so many ways to sanely implement the same functionality.

Ok, how can you explain [this](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/85369b31be6d44861252931a1a04b975e3a9f8d7/Gopkg.toml#L23-L27) and [this](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/785dd83c9390352acec09d5564934727bb1e3200/Gopkg.toml#L1-L5)? It is taken verbatim with comments and formatting. I doubt there is only the single way to write that sentence.

**Comment by slintes** [comment]
Just curious: even if it would be a fork, what is problem? Both use the Apache v2 license which allows it afaik. 
Disclaimer: I'm a customer of Hetzer only

**Comment by AlekSi** [comment]
Apache license, like most open source software licenses, requires attribution. If DigitalOcean's code was indeed used, this fact must be mentioned.
