### ISSUE TITLE
ipv6 only cloud host support

### ISSUE THREAD

**Issue by nazarkulyk** [hetznercloud/hcloud-cloud-controller-manager#299]
Actually its not really problem with controller-manager

There is no AAAA DNS address for 'api.hetzner.cloud', so [hcloud-cloud-controller-manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager) just will not work on ipv6 only nodes :(

Can we push hetzner somehow to fix this ?

**Comment by TitusKirch** [comment]
The problem persists. Are there any further updates here?

**Comment by nazarkulyk** [comment]
The idea was not to warn that ipv6 only instances cant be used, but to push hetzner make ipv6 DNS pointer to api host :D

**Comment by simonostendorf** [comment]
The issue is inside our own project (you can see the repo in the mentioned issue). We need the reminder, because our k8s-nodes have to communicate with the hetzner cloud api. 
So as you mentioned in this issue, ipv4 is needed because the DNS pointers for ipv6 are not valid. We also want to push hetzner to ipv6-cloud-api :)
