### ISSUE TITLE
Bare Metal Support

### ISSUE THREAD

**Issue by maaft** [hetznercloud/hcloud-cloud-controller-manager#330]
There is currently a related stale issue #113 which basically asks for the same.

It would be really nice to have bare metal support integrated in this official CCM.

There is also another [fork](https://github.com/syself/hetzner-cloud-controller-manager) by syself that already supports bare metal servers.

What would be required to support bare metal on this official repo? Couldn't you just integrate the fork's changes?

**Comment by MatthiasLohr** [comment]
@LKaemmerling, any information for us on this?

**Comment by apricote** [comment]
What features would you expect from the `cloud-controller-manager` when running on dedicated servers?

We currently have no plan to support this, but I added it to our internal feature requests board.

**Comment by MatthiasLohr** [comment]
Actually, IMHO, not that much...

  * Very first step: Accept them beeing in the cluster, without throwing errors. Ignore them, let's them managy by ourselfes, until the following points will be supported.
  * Automatic labeling of (bare metal) nodes according to its location (zone, etc.).
  * Consideration for cloud load balancers

**Comment by maaft** [comment]
Just want to add that configuration of LB is very important imho. But I'm fine with any progress on this matter.

**Comment by hifi** [comment]
This created a lot of havoc when we added so many bare metal nodes to a mixed cluster that it started eating Hetzner API rate limit faster than it regenerated (over 1 req/s) forcing us to scale it down. It made things even worse that as a side effect it completely broke Terraform as well so we can't keep it running anymore except when adding new nodes as it will lock us out from the API.

We're fine with ignoring them as we manage them by hand anyway so just being able to even add a label to ignore a node would be more than fine so that it doesn't DoS the API.

**Comment by Privatecoder** [comment]
It would be highly appreciated if the ccm would at least ignore bm-nodes carrying the `instance.hetzner.cloud/is-root-server=true` label like the csi does.

I am currently using a fork which also determines the bm-nodes IP address to update loadbalancer targets accordingly.

This is in a k3s hybrid cluster using wireguard-native as flannel-backend.

**Comment by samcday** [comment]
In #342 we've been throwing around the idea of adding a label selector for servers to support more advanced use-cases.

That same functionality could be useful here as a stopgap solution to filtering out BM / non-hcloud servers from hccms view, I think?

Longer term, it'd be better if hccm was more robust in the way it "adopts" Nodes with a backing hcloud server, such that it knows to only adopt the right ones, and leave any other nodes alone.

**Comment by samcday** [comment]
As for load balancers, there's also been talk of a [similar label selector](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/373) in #373.

If a mixed-mode LB is desired, you have a couple of options:

 * Let hccm create a LB and manage the cloud server targets for it. Run something (Terraform, `hcloud` CLI call, web console, w/e) to attach additional Robot servers to this LB.
 *  Create the LB out of band (TF provider, etc), pass the name explicitly in the [`load-balancer.hetzner.cloud/name` annotation](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/7d1cd6a6eef9b22bdcd436bc70b3cf8bfcf39c9d/internal/annotation/load_balancer.go#L41) so that hccm adopts the existing LB.

Take these suggestions with a grain of salt though, as I have not personally tested either of these.

**Comment by guettli** [comment]
We (Syself) maintain a ccm which supports hcloud and hetzner (bare-metal).

https://github.com/syself/hetzner-cloud-controller-manager

If hetznercloud agrees, than we could create a PR to merge our changes.

See related issue: #438

**Comment by qveensi** [comment]
good afternoon, we also need to add bare-metal nodes

**Comment by guettli** [comment]
@qveensi have you tried the ccm from Syself? https://github.com/syself/hetzner-cloud-controller-manager

**Comment by qveensi** [comment]
> @qveensi have you tried the ccm from Syself? https://github.com/syself/hetzner-cloud-controller-manager

I picked up their solution, but I still did not find how to add iron nodes to the cluster, ccm still looks for nodes in hcloud, not robots, and there are no instructions on how to add nodes.

i used chart syself/ccm-hetzner with all the necessary keys in secret, including the login/password for robots.

logs from ccm:
```
I0907 09:23:52.146790       1 event.go:294] "Event occurred" object="k8s-node-2" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="RemovingNode" message="Node k8s-node-2 event: Removing Node k8s-node-2 from Controller"
W0907 09:24:10.109757       1 actual_state_of_world.go:541] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="k8s-node-2" does not exist
I0907 09:24:10.124833       1 range_allocator.go:367] Set node k8s-node-2 PodCIDR to [10.3.68.0/24]
I0907 09:24:12.150695       1 event.go:294] "Event occurred" object="k8s-node-2" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="RegisteredNode" message="Node k8s-node-2 event: Registered Node k8s-node-2 in Controller"
W0907 09:24:19.007274       1 topologycache.go:199] Can't get CPU or zone information for k8s-node-2 node
W0907 09:24:46.685193       1 topologycache.go:199] Can't get CPU or zone information for k8s-node-2 node
```

**Comment by guettli** [comment]
@qveensi I use the Syself CCM with the Syself Cluster API Provider (I work for this company). How did you create your Kubernetes cluster?

**Comment by apricote** [comment]
@qveensi @guettli Could you move this discussion to the Hetzner CCM repo?

**Comment by apricote** [comment]
Hey all! I have created #523 to track the actual implementation. Please follow that issue if you are interested in updates.
