### ISSUE TITLE
Working routes to alias IPs are being deleted by the HCCM

### ISSUE THREAD

**Issue by ppar** [hetznercloud/hcloud-cloud-controller-manager#425]
## Summary:

If the hcloud Network that HCCM is attached to contains a route that points to an _alias_ IP assigned to a server, the HCCM  assumes this route is not functional and deletes it:

```
I0417 13:36:28.843781       1 routes.go:75] "server for route not
found, deleting route in hcloud because the route is not functional"
op="hcloud/ListRoutes" gateway="10.XYZ.0.254"
err="hcloud/hcloudRouteToRoute: hcops/AllServersCache.ByPrivateIP:
10.XYZ.0.254 hcops/AllServersCache.getCache: not found"
```

This is not expected behaviour, because using an alias IP in a route is supported by Hetzner cloud -- so in practice the HCCM is deleting functional routes that should be kept in place.

Version in use: `hetznercloud/hcloud-cloud-controller-manager:v1.15.0`

##  In detail, with context:

I'm trying to run K3S worker/slave nodes without public IPs in an HA cluster, since assigning precious routable IPv4 on them would be wasteful. However, since Hetzner cloud doesn't provide a NAT gateway service, I also need to run my own NAT gateway to provide internet connectivity to them.

Running a simple NAT GW is trivial: `iptables -t nat ...` on a VM with a public and private ip, ask the hcloud network to route 0.0.0.0/0 viat that VM's private IP, and you're done. 

However, an HA K3S cluster also needs an HA NAT gateway. Since there are no floating private IPs in hcloud, the next best option is to run a bunch of redundant servers that function as NAT gateways, choose an *alias* private IP (here `10.XYZ.0.254`) as a Virtual IP, and run keepalived on these servers to assign the alias IP to a currently working server (by hooking in a script that calls the hcloud API whenever the alias IP needs to switch owners). In short:

```
$ hcloud server describe my-cluster-node-01
ID:             SERVER_ID
Public Net:
  IPv4:
    ID:         NNNNN
    IP:         167.NNN.NNN.NNN
Private Net:
  - ID:                 $NETWORK_ID
    Name:               my-cluster-net
    IP:                 10.XYZ.0.11
    Alias IPs:
     -                  10.XYZ.0.254
.... 

$ hcloud network add-route  $NETWORK_ID --destination 0.0.0.0/0 --gateway 10.XYZ.0.254

$ hcloud network describe $NETWORK_ID
ID:             $NETWORK_ID
Name:           my-cluster-net
IP Range:       10.XYZ.0.0/24
Subnets:
  - Type:               cloud
    Network Zone:       eu-central
    IP Range:           10.XYZ.0.0/24
    Gateway:            10.XYZ.0.1
Routes:
  - Destination:        10.42.2.0/24
    Gateway:            10.XYZ.0.2
  - Destination:        10.42.1.0/24
    Gateway:            10.XYZ.0.12
  - Destination:        0.0.0.0/0
    Gateway:            10.XYZ.0.254
  - Destination:        10.42.0.0/24
    Gateway:            10.XYZ.0.11
 ```

As mentioned above, a couple of seconds after adding the 0.0.0.0/0 route, it it vanishes from `hcloud network describe` output -- with the message at the top of the report logged by the HCCM container.

(FWIW -- in this use case, I could probably work around the issue by having the keepaliveds modify the *hcloud network's 0.0.0.0/0 route* instead of the alias IP, pointing it to the relevant server's "primary" private IP, and maybe even dropping the alias IP altogether. 

But conceptually, switching a Virtual IP between gateways would be a more conventional and recognizable pattern, and in general, I suppose HCCM should recognize routes to alias IPs as well.)

**Comment by samcday** [comment]
I wrote [hcloud-fip-k8s](https://github.com/samcday/hcloud-fip-k8s/) primarily so I could experiment with running my own NAT Gateway type of service in hcloud. It might be something you're interested in as well, given what you're trying to do here.

If you use Cilium Egress Gateways in combination with a floating IP, you can get a pretty solid and robust NAT gateway setup. During testing I noticed that Cilium was actually able to keep a TCP session alive (with some packet loss + retransmission) in the middle of the NAT IP changing homes. So technically I'd even call that "HA", though it doesn't support multiple NAT gateways at once ;)

---

As for this specific issue, the code makes it clear it's trying to garbage collect stale routes.

If hccm configures 10.0.0.0/16 -> Node 1, but then Node 1 is deleted in a way that hccm doesn't get a chance to observe and reconcile, then the route 10.0.0.0/16 will stick around until the heat death of the universe. I remember actually running into this bug early last year. I guess I wasn't running the hccm version that [included this fix](https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/238).

The "best" solution to this, IMO, is to add a finalizer to Nodes that have had a route registered, so that hccm can guarantee a cleanup operation before letting the node go away.

Alternatively, hccm could stop aggressively cleaning up "stale" routes, since it can't possibly know that authoritatively, and instead it could only delete a route if it *knows* that route should be pointing somewhere else (i.e 10.0.0.0/16 was for node A with IP 172.0.0.1, which tragically perished, and was callously replaced with node C having IP 172.0.02).

Alternatively alternatively, hccm could be made to allow a `HCLOUD_IGNORE_ROUTES` option, so that any routes contained/intersecting with the provided CIDR are left untouched.

**Comment by apricote** [comment]
A quick for this would be to add the alias IPs to the list of IPs that the server is known by, this would avoid the route being garbage collected. `c.byPrivIP` is used to check the routes through `r.hcloudRouteToRoute(route) -> r.serverCache.ByPrivateIP(route.Gateway)`.

```diff
diff --git a/internal/hcops/server.go b/internal/hcops/server.go
index 1e25fc49..adc94941 100644
--- a/internal/hcops/server.go
+++ b/internal/hcops/server.go
@@ -106,6 +106,10 @@ func (c *AllServersCache) getCache(getSrv func() (*hcloud.Server, bool)) (*hclou
                                continue
                        }
                        c.byPrivIP[n.IP.String()] = srv
+
+                       for _, alias := range n.Aliases {
+                               c.byPrivIP[alias.String()] = srv
+                       }
                }
 
                // Index servers by their names.
```

**Comment by ppar** [comment]
@samcday thanks for the tips, I'll check those out

**Comment by apricote** [comment]
Is this working for you @ppar?

---

I still think that we should add alias IPs in the private network as official endpoints for the node, by returning it as a Node Address of type `InternalIP`, as well as adding it to the cache I mentioned in my last message. I will test this and create a PR if its working.

**Comment by apricote** [comment]
Returning multiple private IPs for `node.status.addresses` does not work in all scenarios. If the `--node-ip` flag is set on the kubelet, only that IP will be returned for its type (internal, external): https://github.com/kubernetes/cloud-provider/blob/22e08785c750bd4610af7198d43ecf72b688e9ed/node/helpers/address.go#L91-L105

After a deep dive into the [k/cloud-provider Routes Controller](https://github.com/kubernetes/cloud-provider/blob/22e08785c750bd4610af7198d43ecf72b688e9ed/controllers/route/route_controller.go#L220-L260) I figured out the following:

- k/c-p cleans up any unused routes itself, by calling [`Routes.DeleteRoute`](https://github.com/kubernetes/cloud-provider/blob/22e08785c750bd4610af7198d43ecf72b688e9ed/cloud.go#L242-L244), which we have to implement.
- It only does this for routes that are within the configured `--cluster-cidr`, so your default route (`0.0.0.0/0`) would not be deleted.
- Bugs mentioned in #238, which introduced the current cleanup behaviour, were triggered by a bug in `DeleteRoute` where we [only delete the route if we can find a server that matches this route](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/892c20e199e1aee64e731aa9f05e9320dfc5d1bd/hcloud/routes.go#L161-L169). But we cant find the deleted servers (as they are deleted) and never delete the routes successfully.

I propose the following fix (and will open PR shortly):

- Fix `DeleteRoute` so it does not require an existing hcloud server. We can simply replace the current logic to find the IP by iterating through all Routes and find the one matching the destination cidr.
- Remove the overzealous cleanup in `ListRoutes`, as all routes for deleted nodes are now removed by k/c-p.

My proposed changes for allowing alias IPs to identify the servers is no longer necessary.
