### ISSUE TITLE
Infinite Loop on Hetzner Heray page (https://accounts.hetzner.com/_ray/pow)

### ISSUE THREAD

**Issue by 0wx** [hetznercloud/hcloud-cloud-controller-manager#705]
### TL;DR

When accessing the login page I keep getting infinite loop in the Heray page, and also my CPU process spike when this happened.

![image](https://github.com/user-attachments/assets/bebaa715-0634-4965-ae41-b2312804527b)

### Expected behavior

can go to login page as usual

### Observed behavior

infinite loop in the Heray page

**Comment by jooola** [comment]
@0wx In order to be able to analyze the access problem, please open a support ticket https://www.hetzner.com/support-center and provide us with the missing information:

- Clear description of the problem
    - What can you see on the browser? (Error page, error codes)
    - What happens on the browser? (Is there an infinite loop in the waiting room, or a timeout?)
- Called URL(s)
- IP addresses (IPv4 and IPv6, available via https://ip.hetzner.com)
- Time of access
- Browser name and version
- Browser plugins
- Operating system and version

Important notes:

## JS and WASM

WebAssembly and Javascript are required for our services, and you need to have enabled them on your browser. If not, you will not be able to use the page. Some browsers deactivate JS and/or WASM by default, and they then need to be manually enabled. This situation usually only occurs on browsers that place a high value on anonymization, such as Tor and Brave.

## Browser

Please make sure that you are using the most current version of your browser. We cannot guarantee that our services will support outdated browsers. We support the most common browsers like Google Chrome, Mozilla Firefox, Microsoft Edge, and Safari.

## Browser plugins

These can cause access problems as each plugin has its own individual functionality. If you have problems with this, you can narrow down the cause by deactivating all plugins and identifying the relevant plugin using the exclusion principle. Please test all plugins and send us a complete list so that we can check this holistically.
