### ISSUE TITLE
Failed to start service controller: the cloud provider does not support external load balancers

### ISSUE THREAD

**Issue by eddiewang** [hetznercloud/hcloud-cloud-controller-manager#89]
```
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
ERROR: logging before flag.Parse: W0923 14:15:18.735927       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ERROR: logging before flag.Parse: W0923 14:15:19.076494       1 controllermanager.go:108] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
ERROR: logging before flag.Parse: W0923 14:15:19.077268       1 authentication.go:55] Authentication is disabled
ERROR: logging before flag.Parse: I0923 14:15:19.077314       1 insecure_serving.go:49] Serving insecurely on [::]:10253
ERROR: logging before flag.Parse: I0923 14:15:19.081243       1 node_controller.go:89] Sending events to api server.
ERROR: logging before flag.Parse: I0923 14:15:19.083792       1 pvlcontroller.go:107] Starting PersistentVolumeLabelController
ERROR: logging before flag.Parse: I0923 14:15:19.083857       1 controller_utils.go:1025] Waiting for caches to sync for persistent volume label controller
ERROR: logging before flag.Parse: E0923 14:15:19.086458       1 controllermanager.go:240] Failed to start service controller: the cloud provider does not support external load balancers
```

I've been having trouble trying to get the load balancers to work properly with hcloud-cloud-controller. I'm using a vanilla build with Kubeone scripts. Does anyone know why the message reads: `ERROR: logging before flag.Parse: E0923 14:15:19.086458       1 controllermanager.go:240] Failed to start service controller: the cloud provider does not support external load balancers`

thanks in advance!

**Comment by arenstar** [comment]
👍  im wondering the same thing

**Comment by LKaemmerling** [comment]
Which version of the cloud controller do you use?

**Comment by pitwegner** [comment]
still appears on version 1.13.2

**Comment by apricote** [comment]
Hey @pitwegner, could you provide me with detailed reproduction steps so I can investigate this?

**Comment by pitwegner** [comment]
actually not sure what changed... This does appear in the logs after the k3s startup, but doesn't prevent it from starting or working correctly for that matter.

**Comment by apricote** [comment]
So the load balancer support works for you? What version of k3s are you using?

**Comment by apricote** [comment]
I checked out where this error is coming from, and this happens when the Load Balancer support is not enabled.

https://github.com/kubernetes/cloud-provider/blob/11e49706691b05e67ac6ca4acae4a2607a739352/app/core.go#L93-L94

You can safely ignore this error if you do not have load balancer support enabled (`HCLOUD_LOAD_BALANCERS_ENABLED=false`).

**Comment by rajendragosavi** [comment]
@apricote Can you share where to enable the Load balancer support here? I am also facing the similar issue with my Openstack provider.

Thanks

**Comment by apricote** [comment]
Hey @rajendragosavi,

this project is not related in any way to OpenStack and we provide no support for it.

If you came here for the log message `Failed to start service controller: the cloud provider does not support external load balancers`: This happens when the `service` controller is enabled on the binary (by default) but the cloud-controller-manager implementation tells the binary that Load Balancers are not supported: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/ad43445c0e945482099561d2bed0a3c8f125e13f/hcloud/cloud.go#L158-L161

**Comment by rajendragosavi** [comment]
@apricote  what is service controller enabled on binary?

**Comment by apricote** [comment]
Please check with your provider.

**Comment by rajendragosavi** [comment]
I am using openstack cloud provider to create k8s cluster on bare metal VMs.

**Comment by apricote** [comment]
Yes, and this is the Hetzner Cloud hcloud-cloud-controller-manager that is not related to OpenStack in any way, so I can not answer your question.

Please ask your OpenStack provider for details on this.
