### ISSUE TITLE
Preserve real client ip with LB

### ISSUE THREAD

**Issue by ditschedev** [hetznercloud/hcloud-cloud-controller-manager#92]
Is there yet a way to preserve the clients real ip through the lb and the nodes as I'am always getting the nodes public ip address?

**Comment by LKaemmerling** [comment]
If you use a service with HTTP the LB automatically adds specific headers with the real IP: https://docs.hetzner.com/cloud/load-balancers/faq/#do-load-balancers-forward-special-http-headers

If you use a service "tcp" this is not possible, you could use proxy protocol for this but keep in mind that your service needs to support proxy protocol.

I close this issue now because it isn't a direct CCM problem. Feel free to ask questions or reopen the issue if you think it is a CCM related problem.
